# Setup
title: Shantanu Prakash
tagline: Trying to live a better life.
url: https://shantanuprakash3.github.io/
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-158593816-1

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Specify the author for blog posts
author:
  name: Shantanu Prakash
  url: https://twitter.com/shantanupracash
  email: shantanuprakash3@gmail.com

# Custom vars
version: 3.0.0
github:
  repo: https://github.com/poole/poole
